version: "3"

services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    container_name: mobsf
    ports:
      - "8000:8000"
    networks:
      - droidkey-net
    restart: always

  backend:
    image: silvatkp/droidkey-backend
    container_name: droidkey_backend
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - mobsf
    networks:
      - droidkey-net
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0

  frontend:
    image: silvatkp/droidkey-frontend
    container_name: droidkey_frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - droidkey-net

networks:
  droidkey-net:
    driver: bridge
