name: Deploy DroidKey

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Backend Docker image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: silvatkp/droidkey-backend:latest

      # Build and push Frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: silvatkp/droidkey-frontend:latest

      # Copy SSH key
      - name: Copy SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Upload docker-compose.yml to Server
      - name: Upload docker-compose.yml to Server
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose.yml droidkeyuser@${{ secrets.SERVER_HOST }}:/home/droidkeyuser/

      # Deploy Application
      - name: Deploy Application
        env:
          DOCKER_HOST: "ssh://droidkeyuser@${{ secrets.SERVER_HOST }}"
        run: |
          ssh -o StrictHostKeyChecking=no droidkeyuser@${{ secrets.SERVER_HOST }} '
            cd /home/droidkeyuser &&
            docker-compose pull &&
            docker-compose up -d
          '
