name: Deploy DroidKey

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: silvatkp/droidkey-backend:latest

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: silvatkp/droidkey-frontend:latest

      - name: Copy SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload docker-compose.yml to Server
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose.yml droidkeyuser@172.191.163.7:/home/droidkeyuser/

      - name: Deploy Application
        env:
          DOCKER_HOST: "ssh://droidkeyuser@172.191.163.7"
        run: |
          ssh -o StrictHostKeyChecking=no droidkeyuser@172.191.163.7 '
            cd /home/droidkeyuser &&
            docker-compose pull &&
            docker-compose up -d
          '
