name: Deploy DroidKey

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Build the backend Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: silvatkp/droidkey-backend:latest

      # Build the frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: silvatkp/droidkey-frontend:latest

      # Deploy to server using SSH
      - name: Deploy services to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: droidkeyuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/deployment/directory
            docker-compose pull
            docker-compose up -d
